name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@v1.5
    secrets: inherit
    with:
      jest-enabled: false
      sonar-enabled: false

